### ISSUE TITLE
As a developer, I need to write a basic Express app so I can start development on the website.

### ISSUE THREAD

**Issue by matthewtessler** [nyu-software-engineering/online-time-tracker#13]
- [ ] Design a express skeleton
- [ ] Develop the express skeleton
- [ ] Deploy a working version of the express application on each members local machine

**Comment by bloombar** [comment]
Dear @nyu-software-engineering/online-time-tracker team - your task board generally looks nice... but not exactly following the Scrum way of doing things... specifically:
- [ ] things in the Sprint backlog should be user stories - they should be phrased the way user stories are always phrased, "As a ____, I want ___, so I ____".  Items in the other.  These user stories should have the 'user story' and '1 - sprint backlog' labels associated with them
- [ ] each user story should be broken up into individual Tasks.  These should have the 'task' label associated with them, as well as whatever other label correctly indicates their current status, i.e. '2 - in process', '3 - awaiting review', or '4 - done'
- [ ] spikes should always have the 'spike' label... i think you've done these correctly
